package com.github.t1.kubee.tools;

import lombok.*;
import lombok.extern.slf4j.Slf4j;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.*;
import java.net.URI;
import java.util.UUID;

import static javax.ws.rs.core.Response.Status.*;

@Slf4j
@Value
@Builder(builderMethodName = "problemDetail")
public class ProblemDetail {
    public static ProblemDetailBuilder badRequest() { return problem(BAD_REQUEST); }

    public static ProblemDetailBuilder notFound() { return problem(NOT_FOUND); }

    public static ProblemDetailBuilder internalServerError() { return problem(INTERNAL_SERVER_ERROR); }

    public static ProblemDetailBuilder badGateway() { return problem(BAD_GATEWAY); }

    public static ProblemDetailBuilder problem(Status status) { return problemDetail().status(status); }


    public static class ProblemDetailBuilder {
        public WebApplicationException exception() {
            ProblemDetail entity = build();
            return new WebApplicationException(entity.toString(), Response.status(status).entity(entity).build());
        }
    }


    /**
     * A URI reference [RFC3986] that identifies the problem type. When dereferenced, it is encouraged to provide
     * human-readable documentation for the problem type (e.g., using HTML).
     */
    private URI type;

    /**
     * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence
     * to occurrence of the problem, except for purposes of localization.
     */
    private String title;

    /** The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. */
    private StatusType status;

    /**
     * The full, human-readable explanation specific to this occurrence of the problem.
     * It MAY change from occurrence to occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * It MAY yield further information if dereferenced.
     */
    private URI instance = URI.create("urn:problem-instance:" + UUID.randomUUID());


    @Override public String toString() {
        StringBuilder out = new StringBuilder();
        append(out, "type", type);
        append(out, "title", title);
        append(out, "status", status.getStatusCode());
        append(out, "detail", detail);
        append(out, "instance", instance);
        return out.toString().trim();
    }

    private void append(StringBuilder out, String title, Object field) {
        if (field != null)
            out.append(title).append(": ").append(field).append("\n");
    }
}
