---
- hosts: appservers
  become: yes

  tasks:
    - name: Copy deployer.war
      copy:
        src: ../../../target/deployer.war
        dest: /opt/wildfly/standalone/deployments/
        # owner: '{{ wildfly_user }}'
        # group: '{{ wildfly_group }}'
        # mode: '0750'
