---
- hosts: appservers
  gather_facts: False
  vars:
    ami_id: ami-0badcc5b522737046 # Red Hat Enterprise Linux 8 (HVM), SSD Volume Type
    keypair: aws
    instance_type: t2.micro
    region: eu-central-1

  tasks:
    - name: Create Wildfly Workers
      ec2:
        group: wildfly-worker
        #        exact_count: 1
        count: 1
        assign_public_ip: yes
        image: "{{ ami_id }}"
        wait: true
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2
